// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

document.addEventListener("DOMContentLoaded", function() {
    var reviewBtn = document.getElementById("review-btn");
    var reviewForm = document.getElementById("review-form");

    reviewBtn.addEventListener("click", function() {
      if (reviewForm.style.display === "none") {
        reviewForm.style.display = "block";
      } else {
        reviewForm.style.display = "none";
      }
    });
  });
